### ISSUE TITLE
FIXME less-precise LineKick goalie.py

### ISSUE THREAD

**Issue by gtrosawa** [RoboJackets/robocup-software#939] opened 2017-03-16 21:06 UTC
# FIXME: what we really want is a less-precise LineKick
        #           this will require a Capture behavior that doesn't wait for the ball to stop

**Comment by jgkamat** [comment] 2017-03-16 22:07
#947, goalie.py is being deprecated. Also I think this is a dupe of something else as well.

**Closed by jgkamat** 2017-03-16 22:07 UTC
