### ISSUE TITLE
Add ability to save and restore robot locations to soccer

### ISSUE THREAD

**Issue by ashaw596** [RoboJackets/robocup-software#530] opened 2016-01-27 18:24 UTC
Currently, we can drag robots and reset the robot positions. It would be great if there was a way to save the current state of the robots and restore it in to allow easier testing plays and things in simulator.

**Comment by justbuchanan** [comment] 2016-01-27 18:32
Duplicate of #363

**Comment by ashaw596** [comment] 2016-01-27 18:49
Its not the same. Saving the current state of the simulator to a config file is an issue of persisstance which is significantly more complicated. This is saving the location in soccer in memory and the restoring it using the currently already implemented communication protocol between soccer and simulator.

**Comment by ashaw596** [comment] 2016-01-27 18:50
Also the other issue #363 sorely lacks detail about the desired feature

**Closed** 2016-02-25 01:31 UTC
Labels: Easy, in progress, soccer, user interface
