### ISSUE TITLE
make robot2015-prog doesn't work on the field control computer

### ISSUE THREAD

**Issue by guyfleeman** [RoboJackets/robocup-software#270] opened 2015-04-13 02:31 UTC
When running prog on the dual-screen Ubuntu machine by the field, the prog fails with the message "no mbed device found".

**Comment by jgkamat** [comment] 2015-04-13 04:01
I'll fix this on tuesday... Were you able to see the mbed in the devices list just fine? If so, something is going wrong in the name parser...

The ubuntu machine on the field is 14:04 right?

**Comment by justbuchanan** [comment] 2015-04-13 04:16
The field computer is on 14.10.

I ran ls before and after and the MBED showed up as "usb-mbed_Microcontroller_101000000000000000000002F7F148E9-0:0" under /dev/disk/by-id.

**Comment by justbuchanan** [comment] 2015-04-13 04:26
I did run this with a different MBED though than the one @guyfleeman used, so there's a chance that one has something messed up.

**Comment by jgkamat** [comment] 2015-04-13 05:16
Hmm, that device ID looks like it would be identified by the script fine, I dont see how that could cause the 'no mbeds found' error. I'll check out @guyfleeman's on tuesday...

**Comment by jgkamat** [comment] 2015-04-15 00:27
I tried it out, and it seemed to work fine. The git repo was not pulled in a while, and ubuntu-setup hadn't been run, so I did both of those, and everything seemed good. Try it out on thursday, and if it dosent work please tell me what shows up under ```/dev/disk/by_id```. If it works out, just close this issue! =)

**Comment by justbuchanan** [comment] 2015-04-17 05:46
@guyfleeman, when you get a chance, go ahead and merge the master branch into mbed-radio so you have the latest stuff - I think this will fix your issues.

**Comment by justbuchanan** [comment] 2015-04-20 00:56
I'm going to go ahead and close this - reopen it if you can reproduce the issue

**Closed by justbuchanan** 2015-04-20 00:56 UTC
Labels: bug, support
