### ISSUE TITLE
Notification when the gameplay system crashes

### ISSUE THREAD

**Issue by ashaw596** [RoboJackets/robocup-software#1034] opened 2017-10-03 23:47 UTC
Right now, if there is a bug, the system just restarts and outputs in the command line. We should make a bigger indicator such as this.

**Comment by jgkamat** [comment] 2017-10-17 16:01
We could use libnotify to send an urgent notification to the system notification daemon, which would be more 'user friendly' I think.

**Comment by CollinAvidano** [comment] 2017-11-29 15:43
I agree with @jgkamat. If its fine with you all I will implement the system notification.

**Comment by jgkamat** [comment] 2017-11-29 16:52
Also, these probably need to have an option to turn this off for debugging. While testing, it's common to have exception loops, and we don't want to attack people's notifications. At least we should throttle or digest these.

Also see #591, which is basically a duplicate of this.

**Comment by jgkamat** [comment] 2017-11-29 16:53
Also, the command for interacting with system notifications is notify-send.

Ex: `notify-send "hello" "world"`

however, if you find a 'libnotify' interface to python, that might be easier to use.

**Closed** 2022-07-12 13:47 UTC
Labels: area / ui, priority / wishlist, exp / adept (2)
